load("//bazel:ps_cc_rules.bzl", "ps_cc_library")

ps_cc_library(
    name = "job_schedule",
    srcs = ["job_schedule.cpp"],
    hdrs = ["job_schedule.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "knapsack",
    srcs = ["knapsack.cpp"],
    hdrs = ["knapsack.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "traveling_salesman",
    srcs = ["traveling_salesman.cpp"],
    hdrs = ["traveling_salesman.h"],
    visibility = [":__subpackages__"],
    deps = [
        "//utils",
    ],
)
