load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary")

filegroup(
    name = "images",
    srcs = glob(["data/**"]),
)

py_binary(
    name = "model",
    srcs = ["model.py"],
    data = [
        ":images",
        "//ai/deep_learning/dataset:cat_and_non-cat",
    ],
    main = "model.py",
    deps = [
        "@pypi//h5py",
        "@pypi//matplotlib",
        "@pypi//numpy",
    ],
)

cc_library(
    name = "image_dataset",
    srcs = ["image_dataset.cpp"],
    hdrs = ["image_dataset.h"],
    data = ["//ai/deep_learning/dataset:cat_and_non-cat"],
    deps = [
        "@hdf5//:hdf5_cpp",
    ],
)

cc_binary(
    name = "logistic_regression",
    srcs = ["main.cpp"],
    deps = [":image_dataset"],
)
