module(name = "ps_monorepo")

bazel_dep(name = "catch2", version = "3.12.0")
bazel_dep(name = "eigen", version = "5.0.1")
bazel_dep(name = "grpc", version = "1.80.0")
bazel_dep(name = "nlohmann_json", version = "3.12.0")
bazel_dep(name = "protobuf", version = "33.4")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "rules_cuda", version = "0.2.5")
bazel_dep(name = "rules_qt", version = "0.0.6")
bazel_dep(name = "spdlog", version = "1.17.0")
bazel_dep(name = "sqlite3", version = "3.51.2")
