load("@rules_cc//cc:defs.bzl", "cc_test")

filegroup(
    name = "data",
    srcs = glob(["data/**"]),
)

cc_test(
    name = "job_schedule_test",
    size = "small",
    srcs = ["job_schedule_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/other:job_schedule",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "knapsack_test",
    size = "small",
    srcs = ["knapsack_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/other:knapsack",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "traveling_salesman_test",
    size = "small",
    srcs = ["traveling_salesman_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/other:traveling_salesman",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "traveling_salesman_large_test",
    size = "enormous",
    timeout = "moderate",
    srcs = ["traveling_salesman_large_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/other:traveling_salesman",
        "@catch2//:catch2_main",
    ],
)
