load("//bazel:ps_cc_rules.bzl", "ps_cc_library")

ps_cc_library(
    name = "recursion",
    srcs = ["recursion.cpp"],
    hdrs = ["recursion.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "hacker_rank",
    srcs = ["hacker_rank.cpp"],
    hdrs = ["hacker_rank.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "circular_queue",
    srcs = ["circular_queue.cpp"],
    hdrs = ["circular_queue.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "circular_buffer",
    srcs = ["circular_buffer.cpp"],
    hdrs = ["circular_buffer.h"],
    visibility = [":__subpackages__"],
)
