load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "str_int_test",
    size = "small",
    srcs = ["str_int_test.cpp"],
    deps = [
        "//sandbox/roblox:str_int",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "int_test",
    size = "small",
    srcs = ["int_test.cpp"],
    deps = [
        "//sandbox/roblox:int",
        "@catch2//:catch2_main",
    ],
)
