load("@rules_cc//cc:defs.bzl", "cc_test")

filegroup(
    name = "data",
    srcs = glob(["data/**"]),
)

cc_test(
    name = "karger_mincut_graph_test",
    size = "small",
    srcs = ["karger_mincut_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:karger_mincut_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "karger_mincut_graph_test_big",
    size = "small",
    timeout = "eternal",
    srcs = ["karger_mincut_graph_test_big.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:karger_mincut_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "breadth_first_graph_test",
    size = "small",
    srcs = ["breadth_first_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:breadth_first_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "strongly_connected_graph_test",
    size = "small",
    srcs = ["strongly_connected_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:strongly_connected_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "strongly_connected_graph_test_big",
    size = "enormous",
    timeout = "short",
    srcs = ["strongly_connected_graph_test_big.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:strongly_connected_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "dijkstra_graph_test",
    size = "small",
    srcs = ["dijkstra_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:dijkstra_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "prim_min_spanning_graph_test",
    size = "small",
    srcs = ["prim_min_spanning_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:prim_min_spanning_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "kruskal_min_spanning_graph_test",
    size = "small",
    srcs = ["kruskal_min_spanning_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:kruskal_min_spanning_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "bellman_ford_graph_test",
    size = "small",
    srcs = ["bellman_ford_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:bellman_ford_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "all_pair_shortest_path_graph_test",
    size = "small",
    srcs = ["all_pair_shortest_path_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:all_pair_shortest_path_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "all_pair_shortest_path_graph_large_test",
    size = "enormous",
    srcs = ["all_pair_shortest_path_graph_large_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:all_pair_shortest_path_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "bit_vertex_clustering_graph_test",
    size = "enormous",
    srcs = ["bit_vertex_clustering_graph_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/graph:bit_vertex_clustering_graph",
        "//utils",
        "@catch2//:catch2_main",
    ],
)
