load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:ps_cc_rules.bzl", "ps_cc_library")

ps_cc_library(
    name = "algo",
    srcs = ["algo.cpp"],
    hdrs = ["algo.h"],
    visibility = [
        ":__subpackages__",
        "//project_euler:__subpackages__",
    ],
    deps = ["@eigen"],
)

ps_cc_library(
    name = "small_primes",
    srcs = ["small_primes.cpp"],
    hdrs = ["small_primes.h"],
    visibility = [
        ":__subpackages__",
        "//project_euler:__subpackages__",
    ],
)

ps_cc_library(
    name = "sorting",
    srcs = ["sorting.cpp"],
    hdrs = ["sorting.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":algo",
    ],
)

ps_cc_library(
    name = "tower_of_hanoi",
    srcs = ["tower_of_hanoi.cpp"],
    hdrs = ["tower_of_hanoi.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "singly_linked_list",
    srcs = ["singly_linked_list.cpp"],
    hdrs = ["singly_linked_list.h"],
    visibility = [
        ":__subpackages__",
        "//algo/prep/epi:__pkg__",
    ],
    deps = [
        "//utils:class_helper",
    ],
)

ps_cc_library(
    name = "binary_tree",
    hdrs = [
        "binary_tree.h",
    ],
    visibility = [
        ":__subpackages__",
        "//algo/prep/epi:__pkg__",
    ],
    deps = [
        "//utils:class_helper",
    ],
)

ps_cc_library(
    name = "binary_search_tree",
    hdrs = [
        "binary_search_tree.h",
    ],
    visibility = [
        ":__subpackages__",
        "//algo/prep/epi/test:__pkg__",
    ],
    deps = [
        ":binary_tree",
        "@spdlog",
    ],
)

ps_cc_library(
    name = "min_heap",
    hdrs = ["min_heap.h"],
    visibility = [
        "//algo:__subpackages__",
    ],
)

ps_cc_library(
    name = "huffman_code",
    srcs = ["huffman_code.cpp"],
    hdrs = ["huffman_code.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":min_heap",
    ],
)

ps_cc_library(
    name = "hash_table",
    srcs = ["hash_table.cpp"],
    hdrs = ["hash_table.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":small_primes",
    ],
)

cc_library(
    name = "lru_cache",
    srcs = ["lru_cache.cpp"],
    hdrs = ["lru_cache.h"],
    visibility = [":__subpackages__"],
)

cc_library(
    name = "trie",
    srcs = ["trie.cpp"],
    hdrs = ["trie.h"],
    visibility = [":__subpackages__"],
)
