load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "model_reader_test",
    size = "small",
    srcs = ["model_reader_test.cpp"],
    data = [
        "//viz/data:models",
    ],
    deps = [
        "//viz/geometry:model_reader",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "gltf_reader_test",
    size = "small",
    srcs = ["gltf_reader_test.cpp"],
    data = [
        "//viz/data:models",
    ],
    deps = [
        "//viz/geometry:gltf_reader",
        "@catch2//:catch2_main",
    ],
)
