load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//bazel:ps_cc_rules.bzl", "ps_cc_library")

ps_cc_library(
    name = "str_int",
    srcs = ["str_int.cpp"],
    hdrs = ["str_int.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "int",
    srcs = ["int.cpp"],
    hdrs = ["int.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "multiples",
    srcs = ["multiples.cpp"],
    hdrs = ["multiples.h"],
    deps = [
        ":int",
    ],
)

cc_binary(
    name = "roblox",
    srcs = ["main.cpp"],
    deps = [
        ":multiples",
        ":str_int",
    ],
)
