load("//bazel:ps_cc_rules.bzl", "ps_cc_library")

ps_cc_library(
    name = "primitives",
    srcs = ["primitives.cpp"],
    hdrs = ["primitives.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "arrays",
    srcs = ["arrays.cpp"],
    hdrs = ["arrays.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "strings",
    srcs = ["strings.cpp"],
    hdrs = ["strings.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "linked_lists",
    srcs = ["linked_lists.cpp"],
    hdrs = ["linked_lists.h"],
    visibility = [":__subpackages__"],
    deps = [
        "//algo/basic:singly_linked_list",
    ],
)

ps_cc_library(
    name = "stacks_and_queues",
    srcs = ["stacks_and_queues.cpp"],
    hdrs = ["stacks_and_queues.h"],
    visibility = [":__subpackages__"],
)

ps_cc_library(
    name = "binary_trees",
    srcs = ["binary_trees.cpp"],
    hdrs = ["binary_trees.h"],
    visibility = [":__subpackages__"],
    deps = [
        "//algo/basic:binary_tree",
    ],
)
