load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "recursion_test",
    size = "small",
    srcs = ["recursion_test.cpp"],
    deps = [
        "//algo/prep:recursion",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "hacker_rank_test",
    size = "small",
    srcs = ["hacker_rank_test.cpp"],
    deps = [
        "//algo/prep:hacker_rank",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "circular_queue_test",
    size = "small",
    srcs = ["circular_queue_test.cpp"],
    deps = [
        "//algo/prep:circular_queue",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "circular_buffer_test",
    size = "small",
    srcs = ["circular_buffer_test.cpp"],
    deps = [
        "//algo/prep:circular_buffer",
        "@catch2//:catch2_main",
    ],
)
