load("@rules_cc//cc:cc_test.bzl", "cc_test")

filegroup(
    name = "data",
    srcs = glob(["data/**"]),
)

cc_test(
    name = "algo_test",
    size = "small",
    srcs = ["algo_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/basic:algo",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "small_primes_test",
    size = "small",
    srcs = ["small_primes_test.cpp"],
    deps = [
        "//algo/basic:small_primes",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "sorting_test",
    size = "small",
    srcs = ["sorting_test.cpp"],
    deps = [
        "//algo/basic:sorting",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "tower_of_hanoi_test",
    size = "small",
    srcs = ["tower_of_hanoi_test.cpp"],
    deps = [
        "//algo/basic:tower_of_hanoi",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "singly_linked_list_test",
    size = "small",
    srcs = ["singly_linked_list_test.cpp"],
    deps = [
        "//algo/basic:singly_linked_list",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "binary_tree_test",
    size = "small",
    srcs = ["binary_tree_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/basic:binary_tree",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "binary_search_tree_test",
    size = "small",
    srcs = ["binary_search_tree_test.cpp"],
    deps = [
        "//algo/basic:binary_search_tree",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "min_heap_test",
    size = "small",
    srcs = ["min_heap_test.cpp"],
    deps = [
        "//algo/basic:min_heap",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "huffman_code_test",
    size = "small",
    srcs = ["huffman_code_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/basic:huffman_code",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "hash_table_test",
    size = "small",
    srcs = ["hash_table_test.cpp"],
    data = ["data"],
    deps = [
        "//algo/basic:hash_table",
        "//utils",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "lru_cache_test",
    size = "small",
    srcs = ["lru_cache_test.cpp"],
    deps = [
        "//algo/basic:lru_cache",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "trie_test",
    size = "small",
    srcs = ["trie_test.cpp"],
    deps = [
        "//algo/basic:trie",
        "@catch2//:catch2_main",
    ],
)
