load("//bazel:ps_cc_rules.bzl", "ps_cc_library")

ps_cc_library(
    name = "graph",
    hdrs = [
        "graph.h",
    ],
)

ps_cc_library(
    name = "karger_mincut_graph",
    srcs = ["karger_mincut_graph.cpp"],
    hdrs = ["karger_mincut_graph.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":graph",
        "//utils:class_helper",
    ],
)

ps_cc_library(
    name = "breadth_first_graph",
    srcs = ["breadth_first_graph.cpp"],
    hdrs = ["breadth_first_graph.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":graph",
    ],
)

ps_cc_library(
    name = "strongly_connected_graph",
    srcs = ["strongly_connected_graph.cpp"],
    hdrs = ["strongly_connected_graph.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":graph",
        "//utils:class_helper",
    ],
)

ps_cc_library(
    name = "dijkstra_graph",
    srcs = ["dijkstra_graph.cpp"],
    hdrs = ["dijkstra_graph.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":graph",
        "//algo/basic:min_heap",
    ],
)

ps_cc_library(
    name = "prim_min_spanning_graph",
    srcs = ["prim_min_spanning_graph.cpp"],
    hdrs = ["prim_min_spanning_graph.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":graph",
        "//algo/basic:min_heap",
        "//utils:class_helper",
    ],
)

ps_cc_library(
    name = "kruskal_min_spanning_graph",
    srcs = ["kruskal_min_spanning_graph.cpp"],
    hdrs = ["kruskal_min_spanning_graph.h"],
    visibility = [":__subpackages__"],
    deps = [
        ":graph",
        "//utils:class_helper",
    ],
)

ps_cc_library(
    name = "bellman_ford_graph",
    srcs = ["bellman_ford_graph.cpp"],
    hdrs = ["bellman_ford_graph.h"],
    visibility = [":__subpackages__"],
    deps = [":graph"],
)

ps_cc_library(
    name = "all_pair_shortest_path_graph",
    srcs = ["all_pair_shortest_path_graph.cpp"],
    hdrs = ["all_pair_shortest_path_graph.h"],
    visibility = [":__subpackages__"],
    deps = [":graph"],
)

ps_cc_library(
    name = "bit_vertex_clustering_graph",
    srcs = ["bit_vertex_clustering_graph.cpp"],
    hdrs = ["bit_vertex_clustering_graph.h"],
    visibility = [":__subpackages__"],
)
