load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "primitives_test",
    size = "small",
    srcs = ["primitives_test.cpp"],
    deps = [
        "//algo/prep/epi:primitives",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "arrays_test",
    size = "small",
    srcs = ["arrays_test.cpp"],
    deps = [
        "//algo/prep/epi:arrays",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "strings_test",
    size = "small",
    srcs = ["strings_test.cpp"],
    deps = [
        "//algo/prep/epi:strings",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "linked_lists_test",
    size = "small",
    srcs = ["linked_lists_test.cpp"],
    deps = [
        "//algo/prep/epi:linked_lists",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "stacks_and_queues_test",
    size = "small",
    srcs = ["stacks_and_queues_test.cpp"],
    deps = [
        "//algo/prep/epi:stacks_and_queues",
        "@catch2//:catch2_main",
    ],
)
