load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "primitives_test",
    size = "small",
    srcs = ["primitives_test.cpp"],
    deps = [
        "//algo/prep/epi:primitives",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "arrays_test",
    size = "small",
    srcs = ["arrays_test.cpp"],
    deps = [
        "//algo/prep/epi:arrays",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "strings_test",
    size = "small",
    srcs = ["strings_test.cpp"],
    deps = [
        "//algo/prep/epi:strings",
        "@catch2//:catch2_main",
    ],
)
