load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "ModelReaderTest",
    size = "small",
    srcs = ["ModelReaderTest.cpp"],
    data = [
        "//graphics/data:models",
    ],
    deps = [
        "//graphics/geometry:ModelReader",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "gltf_reader_test",
    size = "small",
    srcs = ["gltf_reader_test.cpp"],
    data = [
        "//graphics/data:models",
    ],
    deps = [
        "//graphics/geometry:gltf_reader",
        "@catch2//:catch2_main",
    ],
)
